name: trento-bayes
dependencies:
  - python==3.7
  - h5py==2.10.0
  - numpy==1.17.2
  - matplotlib==3.1.1
  - scikit-learn==0.21.3
  - scipy==1.3.1
  - notebook==6.0.2
  - pip
  - pip:
    - -r file:requirements.txt
